name: Run Daily Report smforst Hashtag
on:
  schedule:
    - cron: "0 4 * * *" # Run every day at 4 UTC
  push:
    branches:
      - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install -e . 
          pip install tweepy
          pip install -r requirements.txt

      - name: Generate Daily Hashtag Stats
        env: #assign variables
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          osmsg  --country turkey syria --format csv image --tags 'building' 'highway' 'waterway' 'amenity' --name stats --all_tags --hashtags smforst --charts --summary --length highway --update --name stats/smforst/Daily/stats --force

      - name: add stats to git

        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          base_dir=stats/smforst/Daily

          mkdir -p $base_dir/charts/
          
          cp *.csv $base_dir/
          cp *.png $base_dir/charts/
          mv summary.md $base_dir/Readme.md
          cp stats_metadata.json $base_dir/stats_metadata.json

          git add -f $base_dir/*

          git commit -m "Updated Daily smforst stats"
          git push
