name: Test App
on:
  push:
    paths-ignore:
      - ".github/**"
      - "frontend/**"
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install -e . 
          pip install tweepy
          pip install -r requirements.txt

      - name: Generate Last hour stats
        env: #assign variables
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          osmsg  --format csv image --last_hour --tags 'building' 'highway' 'waterway' 'amenity' --name stats --all_tags --changeset --summary --charts
