name: Run Weekly Report Hotosm Hashtag
on:
  schedule:
    - cron: "0 2 * * MON" # Run every Monday at 2
  # push:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install -e . 
          pip install tweepy
          pip install -r requirements.txt

      - name: Generate Weekly Hashtag Stats
        run: |
          osmsg  --url "https://planet.openstreetmap.org/replication/day" --format csv image --last_week --tags 'building' 'highway' 'waterway' 'amenity' --name stats/hotosm/Weekly/stats --all_tags --read_from_metadata stats/hotosm/Weekly/stats_metadata.json --hashtags hotosm --force --charts --summary  --meta

      - name: add stats to git

        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          
          base_dir=stats/hotosm/Weekly

          mkdir -p $base_dir
          mv $base_dir/stats_summary.md $base_dir/Readme.md
          git add -f $base_dir/*

          git commit -m "Updated Weekly hotosm stats"
          git push

      - name: Tweet Stats
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --git $commit_id --tweet 'Tasking Manager Last Week' --name stats/hotosm/Weekly/stats --mention '@hotosm'

