name: Run Daily Report Hotosm Hashtag
on:
  schedule:
    - cron: "0 0 * * MON" # Run every Monday
  # push:
  #   branches:
  #     - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install -e . 
          pip install tweepy

      - name: Generate Daily Hashtag Stats
        run: |
          osmsg  --url "https://planet.openstreetmap.org/replication/day" --format csv image --extract_last_week --tags 'building' 'highway' 'waterway' 'amenity' --name stats --wild_tags --read_from_metadata stats/hotosm/Weekly/stats_metadata.json --hashtags hotosm

      - name: add stats to git

        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          cp *.csv stats/hotosm/Weekly/hotosm/weekly_stats.csv
          cp stats_metadata.json stats/hotosm/Weekly/hotosm/stats_metadata.json

          git add -f stats/hotosm/Weekly/hotosm/weekly_stats.csv
          git add -f stats/hotosm/Weekly/hotosm/stats_metadata.json
          git commit -m "Updated Weekly hotosm stats"
          git push

      - name: Tweet Stats
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --tweet_hotosm --tweet_last_week --git $commit_id
