name: Run Weekly Report
on:
  # schedule:
    #  - cron: '0 7 * * *' # Run every day at 6 UTC
  push:
    branches:
      - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name : Install Osmium 
        run :
          sudo apt-get install -y osmium-tool

      - name : Install necessary dependecies  
        run : |
          pip install flare-floss
          pip install -e . 
          pip install tweepy

      - name : Generate Weekly Stats
        env: #assign variables 
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
           osmsg --rows 100  --url "https://planet.openstreetmap.org/replication/day" --username '${{ secrets.OSM_USERNAME }}' --password '${{ secrets.OSM_PASSWORD }}' --format csv image --extract_last_week --tags 'building' 'highway' 'waterway' 'amenity' 'landuse' 'natural' --name stats 
      - name : Tweet Stats 
        env: #assign variables 
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run : |
          python tweet.py --tweet_last_week --tweet_global
      - name: Upload stats to Github 
        run : |
            git config --global user.email "skshitizraj@gmail.com"
            git config --global user.name "kshitijrajsharma"
            mv *.csv stats/Global/Weekly/weekly_global_stats.csv
            git add -f stats/Global/Weekly/weekly_global_stats.csv
            git commit -m "Updated weekly global stats"
            git push



