name: Run Weekly Report Global
on:
  schedule:
    - cron: "0 0 * * MON" # Run every Monday
  push:
    branches:
      - master
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Osmium
        run: sudo apt-get install -y osmium-tool

      - name: Install necessary dependecies
        run: |
          pip install flare-floss
          pip install -e . 
          pip install tweepy
          pip install -r requirements.txt

      - name: Generate Weekly Stats
        env: #assign variables
          OSM_USERNAME: ${{ secrets.OSM_USERNAME }}
          OSM_PASSWORD: ${{ secrets.OSM_PASSWORD }}
        run: |
          osmsg --url "https://planet.openstreetmap.org/replication/day" --format csv image --extract_last_week --tags 'building' 'highway' 'waterway' 'amenity' --name stats --read_from_metadata stats/Global/Weekly/stats_metadata.json --wild_tags --include_changeset_meta

      - name: Upload stats to Github
        run: |
          git pull
          git config --global user.email "skshitizraj@gmail.com"
          git config --global user.name "kshitijrajsharma"
          cp *.csv stats/Global/Weekly/weekly_global_stats.csv
          cp stats_metadata.json stats/Global/Weekly/stats_metadata.json

          git add -f stats/Global/Weekly/weekly_global_stats.csv
          git add -f stats/Global/Weekly/stats_metadata.json

          git commit -m "Updated Weekly Global Stats"
          git push

      - name: Tweet Stats
        env: #assign variables
          API_KEY: ${{ secrets.API_KEY }}
          API_KEY_SECRET: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          commit_id=$(git rev-parse --short HEAD)
          python tweet.py --tweet_last_week --tweet_global --git $commit_id
          mv meta.md stats/Global/Weekly/README.md
          mv *.png stats/Global/Weekly/charts/
          git add -f stats/Global/Weekly/README.md
          git add -f stats/Global/Weekly/charts/
          git commit -m "Updated Readme Weekly Global"
          git push
